# Generated by Django 5.2.5 on 2025-09-03 05:25

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, validators=[accounts.models.validate_age]
            ),
        ),
    ]
